const express = require('express');
const swaggerJsdoc = require('swagger-jsdoc');
const swaggerUi = require('swagger-ui-express');

const options = {
  swaggerDefinition: {
    info: {
      title: 'Test API',
      version: '1.0.0',
      description: 'Test Express API with autogenerated swagger doc',
    },
  },
  apis: [`${__dirname}/server.js`],
};

const specs = swaggerJsdoc(options);

const app = express();

/**
 * @swagger
 * /users:
 *    get:
 *      description: return all users
 */
app.get('/users', (req, res) => res.json({ users: [] }));

/**
 * @swagger
 * /jobs:
 *    get:
 *      description: return all jobs
 */
app.get('/jobs', (req, res) => res.json({ users: [] }));

app.use('/', swaggerUi.serve);
app.get('/api-docs', swaggerUi.setup(specs));

// eslint-disable-next-line
app.listen(3000, () => console.log('Listening...'));
